#!/usr/bin/env bash
# a Bash script that will display information about subdomains
# awk will extract data passed before it
# Usage: ./0-world_wide_web <domain> <optional subdomain>
# ./0-world_wide_web kenyanastro.tech www

dns_info() {
    RecAndIp=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $RecAndIp" | awk '{print "The subdomain "$1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    dns_info "$1" "www"
    dns_info "$1" "lb-01"
    dns_info "$1" "web-01"
    dns_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    dns_info "$1" "$2"
fi  
