#!/usr/bin/env bash
# get updates and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# configure nginx to listen on port 80
ufw allow 'Nginx HTTP'

# return a page that contains the string
# When querying Nginx at its root / with a GET request (requesting a page) using curl
echo 'Hello World!' >> /var/www/html/index.html

# Restart Nginx to apply the changes
sudo /etc/init.d/nginx restart
