#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# update machine and install nginx
sudo apt-get update
sudo apt-get install -y nginx 

# return a html page with hello world
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# custom 404 page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# server configuration 
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://help.dreamhost.com/hc/en-us/articles/216456087-Creating-redirects-with-Nginx;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default

# restart to apply changes to nginx server
sudo service nginx restart
