#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

#Distribute requests using a roundrobin algorithm
#Configure HAproxy so that it send traffic to web-01 and web-02
#edit config file
server_config=\
"
frontend kenyanastro-frontend
        bind *:80
        mode http
        default_backend kenyanastro-backend
backend kenyanastro-backend
        balance roundrobin
        mode http
        server 126535-web-01 54.237.209.214:80 check
        server 126535-web-02 54.86.127.182:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

#enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
