#!/usr/bin/env bash
# display lines containing the bash word
# allowing to easily get the PID of Bash process
# shellcheck disable=SC2009
# disable error arrising from not using pgrep
ps auxf | grep bash
